//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.datacredito1.com/CaltecService", ConfigurationName="clsCaltecServiceSoap")]
public interface clsCaltecServiceSoap
{
    
    // CODEGEN: Generating message contract since element name Username from namespace http://www.datacredito1.com/CaltecService is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://www.datacredito1.com/CaltecService/GetXml", ReplyAction="*")]
    GetXmlResponse GetXml(GetXmlRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.datacredito1.com/CaltecService/GetXml", ReplyAction="*")]
    System.Threading.Tasks.Task<GetXmlResponse> GetXmlAsync(GetXmlRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetXmlRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetXml", Namespace="http://www.datacredito1.com/CaltecService", Order=0)]
    public GetXmlRequestBody Body;
    
    public GetXmlRequest()
    {
    }
    
    public GetXmlRequest(GetXmlRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.datacredito1.com/CaltecService")]
public partial class GetXmlRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string Username;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string Password;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
    public string TipoId;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
    public string Id;
    
    public GetXmlRequestBody()
    {
    }
    
    public GetXmlRequestBody(string Username, string Password, string TipoId, string Id)
    {
        this.Username = Username;
        this.Password = Password;
        this.TipoId = TipoId;
        this.Id = Id;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetXmlResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetXmlResponse", Namespace="http://www.datacredito1.com/CaltecService", Order=0)]
    public GetXmlResponseBody Body;
    
    public GetXmlResponse()
    {
    }
    
    public GetXmlResponse(GetXmlResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.datacredito1.com/CaltecService")]
public partial class GetXmlResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string GetXmlResult;
    
    public GetXmlResponseBody()
    {
    }
    
    public GetXmlResponseBody(string GetXmlResult)
    {
        this.GetXmlResult = GetXmlResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface clsCaltecServiceSoapChannel : clsCaltecServiceSoap, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class clsCaltecServiceSoapClient : System.ServiceModel.ClientBase<clsCaltecServiceSoap>, clsCaltecServiceSoap
{
    
    public clsCaltecServiceSoapClient()
    {
    }
    
    public clsCaltecServiceSoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public clsCaltecServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public clsCaltecServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public clsCaltecServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetXmlResponse clsCaltecServiceSoap.GetXml(GetXmlRequest request)
    {
        return base.Channel.GetXml(request);
    }
    
    public string GetXml(string Username, string Password, string TipoId, string Id)
    {
        GetXmlRequest inValue = new GetXmlRequest();
        inValue.Body = new GetXmlRequestBody();
        inValue.Body.Username = Username;
        inValue.Body.Password = Password;
        inValue.Body.TipoId = TipoId;
        inValue.Body.Id = Id;
        GetXmlResponse retVal = ((clsCaltecServiceSoap)(this)).GetXml(inValue);
        return retVal.Body.GetXmlResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetXmlResponse> clsCaltecServiceSoap.GetXmlAsync(GetXmlRequest request)
    {
        return base.Channel.GetXmlAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetXmlResponse> GetXmlAsync(string Username, string Password, string TipoId, string Id)
    {
        GetXmlRequest inValue = new GetXmlRequest();
        inValue.Body = new GetXmlRequestBody();
        inValue.Body.Username = Username;
        inValue.Body.Password = Password;
        inValue.Body.TipoId = TipoId;
        inValue.Body.Id = Id;
        return ((clsCaltecServiceSoap)(this)).GetXmlAsync(inValue);
    }
}
